### PR TITLE
[Editorial] Modernize hyphenation and spelling

### PR DESCRIPTION
**Pull request by MagisterAdamus**
The changes proposed here all still follow British orthography and in all cases involve homophonous substitutions.

### CODE REVIEW

**Comment by acabal** [comment]
`daemon` is not quite the same meaning as `demon` so we should leave that spelling.

`bourne` has been the dominant en-GB spelling for a long time: https://books.google.com/ngrams/graph?content=bourne%2Cbourn&year_start=1800&year_end=2022&corpus=en-GB&smoothing=3&case_insensitive=false

Can you make those tweaks?

**Comment by MagisterAdamus** [comment]
> `daemon` is not quite the same meaning as `demon` so we should leave that spelling.

It seems like `daemon` sometimes reflects a more neutral meaning than `demon` does (according to https://www.etymonline.com/word/demon#etymonline_v_5575), but in _Frankenstein_, the maleficent sense is clearly intended (since, for example, it often is used alongside other obviously negative terms like `fiend`). So I still think that this should be changed. Frankenstein's monster is also described as `demoniacal` in a couple places in the current Standard Ebooks text.
 
> `bourne` has been the dominant en-GB spelling for a long time: https://books.google.com/ngrams/graph?content=bourne%2Cbourn&year_start=1800&year_end=2022&corpus=en-GB&smoothing=3&case_insensitive=false

Whoops! Sorry about that. I'll change that back.

I'm a bit of a Git noob. :sweat_smile: Should I revert the current commit that I made, or simply make a new commit? Or do I have to use `git rebase`?

**Comment by MagisterAdamus** [comment]
I've also found a few more transcription typos since finishing reading the book yesterday. Should I wait for this PR to be closed before submitting those in a separate PR?

**Comment by acabal** [comment]
I think we should leave `daemon` as it is. You can either force push to this PR to fix these issues or just open another PR. For typo fixes, those can be in a separate PR and just open 1 PR for all of the fixes. Thanks!

**Comment by acabal** [comment]
Can you just edit your first commit so that it doesn't include those changes? That way we don't have a ghost commit that just undoes a previous commit. Ultimately this PR should have just 1 commit with all appropriate changes. You can use force push to do that.

**Comment by MagisterAdamus** [comment]
Whoops! Yes, okay, I'll try this again.

**Comment by MagisterAdamus** [comment]
Oh wait, it's not ready yet. I lost the things you'd said to change back.

**Comment by MagisterAdamus** [comment]
OK, this is finally fixed now I think.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
