### PR TITLE
Fix transcription typos and restore some missing words and punctuation

### PR DESCRIPTION
**Pull request by MagisterAdamus**
I've checked all of these changes against the original page scans from the Internet Archive.

### CODE REVIEW

**Comment by acabal** [comment]
Thanks! `reechoed` is one of our spelling updates, can you revert that?

**Comment by MagisterAdamus** [comment]
> Thanks! `reechoed` is one of our spelling updates, can you revert that?

Sure! Give me just a few minutes and I'll do that.

**Comment by MagisterAdamus** [comment]
Done.

**Comment by acabal** [comment]
Thanks

**Pull request merged**
