### PR TITLE
A few small changes

### PR DESCRIPTION
**Pull request by lukasbystricky**

### CODE REVIEW

**Comment by lukasbystricky** [comment]
The new page scans are from the revised 1831 edition we used.

**Comment by acabal** [comment]
Are you sure we want to change the page scans? The current scans are dated 1869, so they are presumably the 1831 edition. The new scans are undated but the foreword is dated 1831. Usually we want the latest scans possible since the idea is that there has been more time to correct typos, add modern typography, etc. 

If the current scans are actually of the wrong edition, then we can update it to the new scans. But if both are of the same edition then we should prefer the one with the later publication date.

**Comment by lukasbystricky** [comment]
Yes, I believe the scans are from the wrong edition. See for example on page 28 in the scans, there's a paragraph that begins with "My father had a sister". This doesn't show up in our edition. The entire chapter has basically been rewritten.

**Comment by acabal** [comment]
OK, thanks!

**Pull request merged**
